/// Flutter icons BaconIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BaconIcons
///      fonts:
///       - asset: fonts/BaconIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class BaconIcons {
  BaconIcons._();

  static const _kFontFam = 'BaconIcons';
  static const String? _kFontPkg = null;

  static const IconData check_circle =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_circle =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information_circle =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning_triangle =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
