import 'package:bacon/src/theme/color_scheme/base.dart';
import 'package:bacon/src/theme/variables/primitives/colors.dart';

class BaconDefaultColorScheme extends BaconColorScheme {
  const BaconDefaultColorScheme._({
    required super.backgroundBrand,
    required super.backgroundBrandLight,
    required super.backgroundPrimary,
    required super.backgroundSecondary,
    required super.backgroundTertiary,
    required super.backgroundInverse,
    required super.backgroundAlwaysWhite,
    required super.backgroundAlwaysDark,
    required super.backgroundAlertDanger,
    required super.backgroundAlertDangerLight,
    required super.backgroundAlertWarning,
    required super.backgroundAlertWarningLight,
    required super.backgroundAlertSuccess,
    required super.backgroundAlertSuccessLight,
    required super.backgroundAlertInformation,
    required super.backgroundAlertInformationLight,
    required super.backgroundAccentPurple,
    required super.backgroundAccentPurpleLight,
    required super.backgroundAccentPink,
    required super.backgroundAccentPinkLight,
    required super.backgroundAccentOrange,
    required super.backgroundAccentOrangeLight,
    required super.backgroundAccentBlue,
    required super.backgroundAccentBlueLight,
    required super.backgroundAccentGreen,
    required super.backgroundAccentGreenLight,
    required super.backgroundAccentYellow,
    required super.backgroundAccentYellowLight,
    required super.backgroundAccentRed,
    required super.backgroundAccentRedLight,
    required super.borderBrand,
    required super.borderPrimary,
    required super.borderSecondary,
    required super.borderInputDefault,
    required super.borderInputHover,
    required super.borderInputFocus,
    required super.borderInputDisabled,
    required super.borderInputActive,
    required super.borderInputInverse,
    required super.borderAlertDanger,
    required super.borderAlertWarning,
    required super.borderAlertSuccess,
    required super.borderAlertInformation,
    required super.borderAccentPurple,
    required super.borderAccentPink,
    required super.borderAccentOrange,
    required super.borderAccentBlue,
    required super.borderAccentGreen,
    required super.borderAccentYellow,
    required super.borderAccentRed,
    required super.contentBrand,
    required super.contentPrimary,
    required super.contentSecondary,
    required super.contentTertiary,
    required super.contentAlwaysWhite,
    required super.contentAlwaysDark,
    required super.contentInverse,
    required super.contentDisabled,
    required super.contentAlertDanger,
    required super.contentAlertWarning,
    required super.contentAlertSuccess,
    required super.contentAlertInformation,
    required super.contentAccentPurple,
    required super.contentAccentPink,
    required super.contentAccentOrange,
    required super.contentAccentBlue,
    required super.contentAccentGreen,
    required super.contentAccentYellow,
    required super.contentAccentRed,
  });

  const BaconDefaultColorScheme.light({
    super.backgroundBrand = BaconColors.colorBrandLight600,
    super.backgroundBrandLight = BaconColors.colorBrandLight100,
    super.backgroundPrimary = BaconColors.colorNeutralLight0,
    super.backgroundSecondary = BaconColors.colorNeutralLight200,
    super.backgroundTertiary = BaconColors.colorNeutralLight300,
    super.backgroundInverse = BaconColors.colorNeutralLight1100,
    super.backgroundAlwaysWhite = BaconColors.colorNeutralLight0,
    super.backgroundAlwaysDark = BaconColors.colorNeutralLight1100,
    super.backgroundAlertDanger = BaconColors.colorRedLight600,
    super.backgroundAlertDangerLight = BaconColors.colorRedLight100,
    super.backgroundAlertWarning = BaconColors.colorOrangeLight600,
    super.backgroundAlertWarningLight = BaconColors.colorOrangeLight100,
    super.backgroundAlertSuccess = BaconColors.colorGreenLight600,
    super.backgroundAlertSuccessLight = BaconColors.colorGreenLight100,
    super.backgroundAlertInformation = BaconColors.colorBlueLight600,
    super.backgroundAlertInformationLight = BaconColors.colorBlueLight100,
    super.backgroundAccentPurple = BaconColors.colorPurpleLight100,
    super.backgroundAccentPurpleLight = BaconColors.colorPurpleLight100,
    super.backgroundAccentPink = BaconColors.colorPinkLight600,
    super.backgroundAccentPinkLight = BaconColors.colorPinkLight100,
    super.backgroundAccentOrange = BaconColors.colorOrangeLight600,
    super.backgroundAccentOrangeLight = BaconColors.colorOrangeLight100,
    super.backgroundAccentBlue = BaconColors.colorBlueLight600,
    super.backgroundAccentBlueLight = BaconColors.colorBlueLight100,
    super.backgroundAccentGreen = BaconColors.colorGreenLight600,
    super.backgroundAccentGreenLight = BaconColors.colorGreenLight100,
    super.backgroundAccentYellow = BaconColors.colorYellowLight100,
    super.backgroundAccentYellowLight = BaconColors.colorYellowLight100,
    super.backgroundAccentRed = BaconColors.colorRedLight600,
    super.backgroundAccentRedLight = BaconColors.colorRedLight100,
    super.borderBrand = BaconColors.colorBrandLight600,
    super.borderPrimary = BaconColors.colorNeutralLight400,
    super.borderSecondary = BaconColors.colorNeutralLight300,
    super.borderInputDefault = BaconColors.colorNeutralLight400,
    super.borderInputHover = BaconColors.colorNeutralLight500,
    super.borderInputFocus = BaconColors.colorNeutralLight600,
    super.borderInputDisabled = BaconColors.colorNeutralLight200,
    super.borderInputActive = BaconColors.colorBrandLight600,
    super.borderInputInverse = BaconColors.colorNeutralLight800,
    super.borderAlertDanger = BaconColors.colorRedLight600,
    super.borderAlertWarning = BaconColors.colorYellowLight600,
    super.borderAlertSuccess = BaconColors.colorGreenLight600,
    super.borderAlertInformation = BaconColors.colorBlueLight600,
    super.borderAccentPurple = BaconColors.colorPurpleLight600,
    super.borderAccentPink = BaconColors.colorPinkLight600,
    super.borderAccentOrange = BaconColors.colorOrangeLight600,
    super.borderAccentBlue = BaconColors.colorBlueLight600,
    super.borderAccentGreen = BaconColors.colorGreenLight600,
    super.borderAccentYellow = BaconColors.colorYellowLight600,
    super.borderAccentRed = BaconColors.colorRedLight600,
    super.contentBrand = BaconColors.colorBrandLight600,
    super.contentPrimary = BaconColors.colorNeutralLight1100,
    super.contentSecondary = BaconColors.colorNeutralLight800,
    super.contentTertiary = BaconColors.colorNeutralLight600,
    super.contentAlwaysWhite = BaconColors.colorNeutralLight0,
    super.contentAlwaysDark = BaconColors.colorNeutralLight1100,
    super.contentInverse = BaconColors.colorNeutralLight0,
    super.contentDisabled = BaconColors.colorNeutralLight500,
    super.contentAlertDanger = BaconColors.colorRedLight600,
    super.contentAlertWarning = BaconColors.colorOrangeLight600,
    super.contentAlertSuccess = BaconColors.colorGreenLight600,
    super.contentAlertInformation = BaconColors.colorBlueLight600,
    super.contentAccentPurple = BaconColors.colorPurpleLight600,
    super.contentAccentPink = BaconColors.colorPinkLight600,
    super.contentAccentOrange = BaconColors.colorOrangeLight600,
    super.contentAccentBlue = BaconColors.colorBlueLight600,
    super.contentAccentGreen = BaconColors.colorGreenLight600,
    super.contentAccentYellow = BaconColors.colorYellowLight600,
    super.contentAccentRed = BaconColors.colorRedLight600,
  });

  const BaconDefaultColorScheme.dark({
    super.backgroundBrand = BaconColors.colorBrandDark600,
    super.backgroundBrandLight = BaconColors.colorBrandDark100,
    super.backgroundPrimary = BaconColors.colorNeutralDark100,
    super.backgroundSecondary = BaconColors.colorNeutralDark0,
    super.backgroundTertiary = BaconColors.colorNeutralDark300,
    super.backgroundInverse = BaconColors.colorNeutralDark1100,
    super.backgroundAlwaysWhite = BaconColors.colorNeutralDark1100,
    super.backgroundAlwaysDark = BaconColors.colorNeutralDark0,
    super.backgroundAlertDanger = BaconColors.colorRedDark600,
    super.backgroundAlertDangerLight = BaconColors.colorRedDark100,
    super.backgroundAlertWarning = BaconColors.colorOrangeDark600,
    super.backgroundAlertWarningLight = BaconColors.colorOrangeDark100,
    super.backgroundAlertSuccess = BaconColors.colorGreenDark600,
    super.backgroundAlertSuccessLight = BaconColors.colorGreenDark100,
    super.backgroundAlertInformation = BaconColors.colorBlueDark600,
    super.backgroundAlertInformationLight = BaconColors.colorBlueDark100,
    super.backgroundAccentPurple = BaconColors.colorPurpleDark100,
    super.backgroundAccentPurpleLight = BaconColors.colorPurpleDark100,
    super.backgroundAccentPink = BaconColors.colorPinkDark600,
    super.backgroundAccentPinkLight = BaconColors.colorPinkDark100,
    super.backgroundAccentOrange = BaconColors.colorOrangeDark600,
    super.backgroundAccentOrangeLight = BaconColors.colorOrangeDark100,
    super.backgroundAccentBlue = BaconColors.colorBlueDark600,
    super.backgroundAccentBlueLight = BaconColors.colorBlueDark100,
    super.backgroundAccentGreen = BaconColors.colorGreenDark600,
    super.backgroundAccentGreenLight = BaconColors.colorGreenDark100,
    super.backgroundAccentYellow = BaconColors.colorYellowDark100,
    super.backgroundAccentYellowLight = BaconColors.colorYellowDark100,
    super.backgroundAccentRed = BaconColors.colorRedDark600,
    super.backgroundAccentRedLight = BaconColors.colorRedDark100,
    super.borderBrand = BaconColors.colorBrandDark600,
    super.borderPrimary = BaconColors.colorNeutralDark400,
    super.borderSecondary = BaconColors.colorNeutralDark300,
    super.borderInputDefault = BaconColors.colorNeutralDark400,
    super.borderInputHover = BaconColors.colorNeutralDark500,
    super.borderInputFocus = BaconColors.colorNeutralDark600,
    super.borderInputDisabled = BaconColors.colorNeutralDark200,
    super.borderInputActive = BaconColors.colorBrandDark600,
    super.borderInputInverse = BaconColors.colorNeutralDark800,
    super.borderAlertDanger = BaconColors.colorRedDark600,
    super.borderAlertWarning = BaconColors.colorYellowDark600,
    super.borderAlertSuccess = BaconColors.colorGreenDark600,
    super.borderAlertInformation = BaconColors.colorBlueDark600,
    super.borderAccentPurple = BaconColors.colorPurpleDark600,
    super.borderAccentPink = BaconColors.colorPinkDark600,
    super.borderAccentOrange = BaconColors.colorOrangeDark600,
    super.borderAccentBlue = BaconColors.colorBlueDark600,
    super.borderAccentGreen = BaconColors.colorGreenDark600,
    super.borderAccentYellow = BaconColors.colorYellowDark600,
    super.borderAccentRed = BaconColors.colorRedDark600,
    super.contentBrand = BaconColors.colorBrandDark600,
    super.contentPrimary = BaconColors.colorNeutralDark1100,
    super.contentSecondary = BaconColors.colorNeutralDark800,
    super.contentTertiary = BaconColors.colorNeutralDark600,
    super.contentAlwaysWhite = BaconColors.colorNeutralDark1100,
    super.contentAlwaysDark = BaconColors.colorNeutralDark0,
    super.contentInverse = BaconColors.colorNeutralDark0,
    super.contentDisabled = BaconColors.colorNeutralDark500,
    super.contentAlertDanger = BaconColors.colorRedDark600,
    super.contentAlertWarning = BaconColors.colorOrangeDark600,
    super.contentAlertSuccess = BaconColors.colorGreenDark600,
    super.contentAlertInformation = BaconColors.colorBlueDark600,
    super.contentAccentPurple = BaconColors.colorPurpleDark600,
    super.contentAccentPink = BaconColors.colorPinkDark600,
    super.contentAccentOrange = BaconColors.colorOrangeDark600,
    super.contentAccentBlue = BaconColors.colorBlueDark600,
    super.contentAccentGreen = BaconColors.colorGreenDark600,
    super.contentAccentYellow = BaconColors.colorYellowDark600,
    super.contentAccentRed = BaconColors.colorRedDark600,
  });

  // factory BaconDefaultColorScheme.from(Brightness brightness) =>
  //     brightness == Brightness.light ? light : dark;

  // static BaconDefaultColorScheme of(BuildContext context) {
  //   return BaconDefaultColorScheme.from(Theme.of(context).brightness);
  // }
}
