import 'package:bacon/src/theme/tokens/modes/base.dart';
import 'package:bacon/src/theme/tokens/variables/primitives/colors.dart';

class BaconDefaultContentColors extends BaconBaseColor {
  const BaconDefaultContentColors({
    required super.brand,
    required super.brandLight,
    required super.primary,
    required super.secondary,
    required super.tertiary,
    required super.inverse,
    required super.disabled,
    required super.alwaysWhite,
    required super.alwaysDark,
    required super.alertDanger,
    required super.alertDangerLight,
    required super.alertWarning,
    required super.alertWarningLight,
    required super.alertSuccess,
    required super.alertSuccessLight,
    required super.alertInformation,
    required super.alertInformationLight,
    required super.accentPurple,
    required super.accentPurpleLight,
    required super.accentPink,
    required super.accentPinkLight,
    required super.accentOrange,
    required super.accentOrangeLight,
    required super.accentBlue,
    required super.accentBlueLight,
    required super.accentGreen,
    required super.accentGreenLight,
    required super.accentYellow,
    required super.accentYellowLight,
    required super.accentRed,
    required super.accentRedLight,
  });

  BaconDefaultContentColors.light()
      : super(
          brand: BaconColors.colorBrandLight600.getColor,
          brandLight: BaconColors.colorBrandLight100.getColor,
          primary: BaconColors.colorNeutralLight1100.getColor,
          secondary: BaconColors.colorNeutralLight800.getColor,
          tertiary: BaconColors.colorNeutralLight600.getColor,
          inverse: BaconColors.colorNeutralLight0.getColor,
          disabled: BaconColors.colorNeutralLight500.getColor,
          alwaysWhite: BaconColors.colorNeutralLight0.getColor,
          alwaysDark: BaconColors.colorNeutralLight1100.getColor,
          alertDanger: BaconColors.colorRedLight600.getColor,
          alertDangerLight: BaconColors.colorRedLight100.getColor,
          alertWarning: BaconColors.colorYellowLight600.getColor,
          alertWarningLight: BaconColors.colorYellowLight100.getColor,
          alertSuccess: BaconColors.colorGreenLight600.getColor,
          alertSuccessLight: BaconColors.colorGreenLight100.getColor,
          alertInformation: BaconColors.colorBlueLight600.getColor,
          alertInformationLight: BaconColors.colorBlueLight100.getColor,
          accentPurple: BaconColors.colorPurpleLight600.getColor,
          accentPurpleLight: BaconColors.colorPurpleLight100.getColor,
          accentPink: BaconColors.colorPinkLight600.getColor,
          accentPinkLight: BaconColors.colorPinkLight100.getColor,
          accentOrange: BaconColors.colorOrangeLight600.getColor,
          accentOrangeLight: BaconColors.colorOrangeLight100.getColor,
          accentBlue: BaconColors.colorBlueLight600.getColor,
          accentBlueLight: BaconColors.colorBlueLight100.getColor,
          accentGreen: BaconColors.colorGreenLight600.getColor,
          accentGreenLight: BaconColors.colorGreenLight100.getColor,
          accentYellow: BaconColors.colorYellowLight100.getColor,
          accentYellowLight: BaconColors.colorYellowLight100.getColor,
          accentRed: BaconColors.colorRedLight600.getColor,
          accentRedLight: BaconColors.colorRedLight100.getColor,
        );

  BaconDefaultContentColors.dark()
      : super(
          brand: BaconColors.colorBrandDark600.getColor,
          brandLight: BaconColors.colorBrandDark100.getColor,
          primary: BaconColors.colorNeutralDark1100.getColor,
          secondary: BaconColors.colorNeutralDark800.getColor,
          tertiary: BaconColors.colorNeutralDark600.getColor,
          inverse: BaconColors.colorNeutralDark0.getColor,
          disabled: BaconColors.colorNeutralDark500.getColor,
          alwaysWhite: BaconColors.colorNeutralDark1100.getColor,
          alwaysDark: BaconColors.colorNeutralDark0.getColor,
          alertDanger: BaconColors.colorRedDark600.getColor,
          alertDangerLight: BaconColors.colorRedDark100.getColor,
          alertWarning: BaconColors.colorYellowDark600.getColor,
          alertWarningLight: BaconColors.colorYellowDark100.getColor,
          alertSuccess: BaconColors.colorGreenDark600.getColor,
          alertSuccessLight: BaconColors.colorGreenDark100.getColor,
          alertInformation: BaconColors.colorBlueDark600.getColor,
          alertInformationLight: BaconColors.colorBlueDark100.getColor,
          accentPurple: BaconColors.colorPurpleDark600.getColor,
          accentPurpleLight: BaconColors.colorPurpleDark100.getColor,
          accentPink: BaconColors.colorPinkDark600.getColor,
          accentPinkLight: BaconColors.colorPinkDark100.getColor,
          accentOrange: BaconColors.colorOrangeDark600.getColor,
          accentOrangeLight: BaconColors.colorOrangeDark100.getColor,
          accentBlue: BaconColors.colorBlueDark600.getColor,
          accentBlueLight: BaconColors.colorBlueDark100.getColor,
          accentGreen: BaconColors.colorGreenDark600.getColor,
          accentGreenLight: BaconColors.colorGreenDark100.getColor,
          accentYellow: BaconColors.colorYellowDark100.getColor,
          accentYellowLight: BaconColors.colorYellowDark100.getColor,
          accentRed: BaconColors.colorRedDark600.getColor,
          accentRedLight: BaconColors.colorRedDark100.getColor,
        );
}
